id: P006983
initial_creation_type: ocr
source_metadata:
  id: bdr:W20840
  title: ཞ་ལུ་དགོན་གྱི་ལོ་རྒྱུས་མདོར་བསྡུས།
  author: ''
  volumes:
    c3c713f08aa546c2ab68a5ad00bba34a:
      image_group_id: I4243
      title: ''
      volume_number: 1
      total_pages: 168
ebook_metadata:
  title: ཞ་ལུ་དགོན་གྱི་ལོ་རྒྱུས་མདོར་བསྡུས།
  author: ''
  sku: P006983
  cover: cover.jpg
  layers:
  - pagination
