id: P006983
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20840
  title: ཞ་ལུ་དགོན་གྱི་ལོ་རྒྱུས་མདོར་བསྡུས།
  author: ''
  volumes:
    c7a7810e2b094be3b57dc8dc452cd39e:
      image_group_id: I4243
      title: ''
      volume_number: 1
      total_pages: 168
      base_file: v001.txt
